name: DCO Check

on:
  pull_request:
    branches: [ main ]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up DCO check
        uses: dcoapp/app@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail-on-error: true
          require-all-contributors: true
          require-signoff: true